### PR TITLE
🌹 Link to related tools in readme

### PR DESCRIPTION
**Pull request by LinusU**
ping @Lutzifer, @jkmathew 

I put the projects in lexicographical order. Did I understand your projects correctly?

I'd be happy to change the descriptions so that we could all use the same in all projects?

happy to see other people doing similar things 👏

### CODE REVIEW

**Comment by Lutzifer** [comment]
👍

**Comment by Lutzifer** [comment]
Added it to https://github.com/num42/icon-resizer-swift

**Comment by jkmathew** [comment]
I will update readme shortly, once I get couple of hours.

**Comment by LinusU** [comment]
Great 👏

**Pull request merged**
